spring.application.name=crud

spring.datasource.url=jdbc:mysql://localhost:3306/userprofile?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
spring.datasource.username= coding
spring.datasource.password= life

jwt.secret=your-secret-key-should-be-very-long-and-secure

spring.messages.basename=messages
spring.messages.encoding=UTF-8

# 스키마 자동 업데이트
#spring.jpa.hibernate.ddl-auto=update